version: '2'

services:  
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mynetwork

  producer:
    image: producer
    volumes:
      - ./initDatabase:/initDatabase
    depends_on:
      - mosquitto
    build:
      context: ./src/Producer/
    networks:
      - mynetwork  

  http-server:
    image: http_image
    depends_on:
      - mosquitto
    build:
      context: ./src/HttpServ/
    ports:
      - "127.0.0.1:8081:8080"
    networks:
      - mynetwork

networks:
  mynetwork:



